[pycodestyle]
max-line-length = 120
exclude=.tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules

[tox]
envlist = {py310,py311}-django{50}
install_command = pip install {opts} "{packages}"
recreate = true

[testenv]
basepython =
    py310: python3.10
    py311: python3.11

deps =
    mock
    django_coverage
    django50: Django>=5.0,<5.1
setenv =
    DJANGO_SETTINGS_MODULE = testapp.settings
commands=
  python manage.py test

[black]
passenv = *
deps =
  setuptools
  black
  allowlist_externals = pytest, black, mypy
commands =
    black: black --check encrypted_model_fields

[pyright]
passenv = *
deps =
  setuptools
  pyright
  allowlist_externals = pytest, black, mypy, pyright
commands =
    pyright: pyright encrypted_model_fields
