[pycodestyle]
max-line-length = 120
exclude=.tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules

[tox]
envlist = {py310,py311}-django{50}
install_command = pip install {opts} "{packages}"
recreate = true

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
deps =
    mock
    django_coverage
    django50: Django>=5.0,<5.1
setenv =
    DEFF_SALT=salt
    DEFF_PASSWORD=password
    DEFF_FETCH_URL_NAME=fetch
commands=
  python manage.py test

[black]
passenv = *
deps =
  setuptools
  black
  allowlist_externals = pytest, black, mypy
commands =
    black: black --check django_encrypted_filefield

[pyright]
passenv = *
deps =
  setuptools
  pyright
  allowlist_externals = pytest, black, mypy, pyright
commands =
    pyright: pyright django_encrypted_filefield
